### ISSUE TITLE
Need help with debugging attaching a ISO

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-server#2197]
I've been working on automating deployment of projects. My goal right now is uploading cloud-init images. For anyone that needs a hand with doing this here is the ansible task i'm using to upload a iso to the node directory. where name is a variable that matches the name of the node.

How to use ansible to upload a file to gns3 via the api. This file will be sent to the project_files/qemu/ dir (at least for qemu, i haven't tested anything else).

This assumes project_id and node_id are variables. project_id can be found in the structure of node_id (which is kind of strange tree wise but whatever)

```yaml
- name: Upload file to GNS3
  delegate_to: localhost
  vars:
    file_to_upload: "/path/to/file/cloud-init.iso"
  ansible.builtin.uri:
    uri: 'http://10.1.1.1:3080/v2/projects/{{project_id}}/nodes/{{node_id}}/files/cloud-init.iso'
    method: POST
    # raw is the default so I don't think this is really needed.
    body_format: raw
    src: "{{ file_to_upload }}"
    headers:
      content-type: application/octet-stream
    # Assuming you have http auth. 
    url_password: "{{ gns3_pass }}"
    url_username: "{{ gns3_user }}"
    force_basic_auth: true
    # Status code should return 201 when successful
    status_code: 201

```

Now the problem i'm having is if I send cdrom_image: cloud_init.iso the http api call will succeed but the cdrom image won't change. I use the fat client and place cloud-init.iso the path will auto expand to a folder in a switch, which is very odd.

@grossmj (or anyone really) Any tips on where to debug setting the cdrom? (like which .py files). I'm already running with -d and I'm not seeing anything, but its possible I missed something. BTW what would be the best way to add logging statements? I'm not above just throwing print statements, just wondering if there is a better way.

Thanks!

**Comment by spikefishjohn** [comment]
Well dang.. 

So the problem seems to be me using the gns3fy ansible module. I'm not sure it has a way to detect that I need to update the properties of a node. I ended up using the uri module to issue a put.

```yaml
- name: Update cdrom image attachment.
  uri:
    url: 'http://10.1.1.1:3080/v2/projects/{{project_id}}/nodes/{{node_id}}'
    method: PUT
    body:
        properties:
          'cdrom_image': '/home/gns3/GNS3/projects/{{project_id}}/project-files/qemu/{{node_id}}/cloud-init.iso'
    body_format: json
    headers:
      Content-Type: "application/json"
    url_password: "{{ gns3_pass }}"
    url_username: "{{ gns3_user }}"
    force_basic_auth: true
    status_code: 200

```
